#!/usr/bin/env python3
"""Build the static parts of veloxitas.com that are generated from content.

Run from the repository root:

    python3 scripts/build.py              # regenerate everything in place
    python3 scripts/build.py --check      # exit 1 if anything is out of date
    python3 scripts/build.py --drafts --out /tmp/preview   # preview drafts

What it does:
  * Turns every Markdown file in content/insights/ (except drafts) into
    /insights/<slug>/index.html, plus the /insights/ index and the RSS feed
    at /insights/feed.xml.
  * Writes /sitemap.xml (homepage, /insights/ and every published article).
  * Fills the generated blocks in index.html:
      - BUILD:FAQ_JSONLD   FAQPage JSON-LD built from the visible FAQ section
      - BUILD:NAV_INSIGHTS "Insights" nav/footer link, once an article exists

Requires: pip install markdown pyyaml
"""

import argparse
import datetime as dt
import html
import json
import re
import shutil
import subprocess
import sys
from email.utils import format_datetime
from pathlib import Path

import markdown
import yaml

ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = ROOT / "content" / "insights"
SITE_URL = "https://veloxitas.com"
CALENDLY_URL = "https://calendly.com/yasmin-veloxitas"
LINKEDIN_URL = "https://www.linkedin.com/in/yasmin-khataie/"
DEFAULT_IMAGE = "/assets/hero-iceberg.jpg"
GENERATED_MARK = "<!-- generated by scripts/build.py -->"

INSIGHTS_TITLE = "Insights | Veloxitas – Yasmin Khataie"
INSIGHTS_INTRO = ("Notes and research on why marketing stops working for established "
                  "B2B companies, and how organisations change the way they're seen.")
AUTHOR_BIO = ("Yasmin Khataie is the founder of Veloxitas, a Dubai-based strategy practice "
              "helping established B2B organisations whose marketing has stopped working, "
              "or who are ready to change how they're seen.")

REQUIRED_FIELDS = ["title", "description", "short_answer", "date"]


# ---------------------------------------------------------------- helpers

def esc(text):
    return html.escape(str(text), quote=True)


def to_date(value, field, source):
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    try:
        return dt.date.fromisoformat(str(value))
    except ValueError:
        sys.exit(f"{source}: '{field}' must be a date like 2026-10-02, got {value!r}")


def human_date(d):
    return f"{d.day} {d.strftime('%B %Y')}"


def abs_url(path):
    return path if path.startswith("http") else SITE_URL + path


def git_date(path):
    """Last commit date of a file, or today if it has uncommitted changes."""
    rel = path.relative_to(ROOT)
    try:
        dirty = subprocess.run(["git", "status", "--porcelain", "--", str(rel)], cwd=ROOT,
                               capture_output=True, text=True, check=True).stdout.strip()
        if not dirty:
            out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", str(rel)], cwd=ROOT,
                                 capture_output=True, text=True, check=True).stdout.strip()
            if out:
                return dt.date.fromisoformat(out)
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    return dt.date.today()


def json_ld(data):
    body = json.dumps(data, indent=2, ensure_ascii=False)
    # keep "</script>" sequences inside strings from closing the tag
    body = body.replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{body}\n</script>'


def replace_block(text, name, content):
    """Replace every <!-- BUILD:name ... --> ... <!-- /BUILD:name --> block."""
    pattern = re.compile(r"(<!-- BUILD:%s(?: [^>]*)? -->)(.*?)(<!-- /BUILD:%s -->)" % (name, name), re.S)
    if not pattern.search(text):
        sys.exit(f"index.html: missing <!-- BUILD:{name} --> block")
    sep = "\n" if "\n" in content else ""
    return pattern.sub(lambda m: m.group(1) + sep + content + sep + m.group(3), text)


# ---------------------------------------------------------------- content

def load_posts(include_drafts):
    posts = []
    for path in sorted(CONTENT_DIR.glob("*.md")):
        if path.name.lower() == "readme.md" or path.name.startswith("_"):
            continue
        raw = path.read_text(encoding="utf-8")
        m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", raw, re.S)
        if not m:
            sys.exit(f"{path}: missing front matter (--- ... ---) at the top")
        meta = yaml.safe_load(m.group(1)) or {}
        if meta.get("draft") and not include_drafts:
            continue
        missing = [f for f in REQUIRED_FIELDS if not meta.get(f)]
        if missing:
            sys.exit(f"{path}: missing front matter field(s): {', '.join(missing)}")
        slug = str(meta.get("slug") or path.stem).strip().strip("/")
        if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", slug):
            sys.exit(f"{path}: slug must be lowercase words joined by hyphens, got {slug!r}")
        date = to_date(meta["date"], "date", path)
        updated = to_date(meta.get("updated") or meta["date"], "updated", path)
        faq = meta.get("faq") or []
        for item in faq:
            if not isinstance(item, dict) or not item.get("q") or not item.get("a"):
                sys.exit(f"{path}: each faq entry needs a 'q' and an 'a'")
        body_html = markdown.markdown(m.group(2), extensions=["extra", "sane_lists"])
        if re.search(r"<h1[\s>]", body_html):
            sys.exit(f"{path}: the article body must not contain a level-1 heading (#); "
                     "the title is the H1. Use ## and ### in the body.")
        posts.append({
            "title": str(meta["title"]).strip(),
            "slug": slug,
            "description": str(meta["description"]).strip(),
            "short_answer": str(meta["short_answer"]).strip(),
            "date": date,
            "updated": max(updated, date),
            "tags": [str(t).strip() for t in (meta.get("tags") or [])],
            "image": str(meta.get("image") or DEFAULT_IMAGE),
            "faq": faq,
            "body": body_html,
            "draft": bool(meta.get("draft")),
            "url": f"/insights/{slug}/",
        })
    slugs = [p["slug"] for p in posts]
    dupes = {s for s in slugs if slugs.count(s) > 1}
    if dupes:
        sys.exit(f"duplicate slug(s): {', '.join(sorted(dupes))}")
    posts.sort(key=lambda p: (p["date"], p["slug"]), reverse=True)
    return posts


def related_posts(post, posts, limit=3):
    tags = set(post["tags"])
    if not tags:
        return []
    return [p for p in posts if p is not post and tags & set(p["tags"])][:limit]


# ---------------------------------------------------------------- templates

def nav_insights_link(has_posts):
    return '<a href="/insights/">Insights</a>' if has_posts else ""


def page(head, body, has_posts):
    insights = nav_insights_link(has_posts)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
{GENERATED_MARK}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{head}
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="alternate" type="application/rss+xml" title="Veloxitas Insights" href="/insights/feed.xml">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,500;0,600;1,500;1,600&family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/styles.css">
</head>
<body>

<a class="skip-link" href="#main">Skip to content</a>

<div class="site-top">
  <header class="site-header">
    <div class="container header-inner">
      <a href="/" class="logo" aria-label="Veloxitas — home">
        <img src="/assets/logo-veloxitas.webp" alt="Veloxitas" class="logo-img" width="400" height="88">
      </a>
      <nav class="main-nav" aria-label="Main">
        <a href="/#story">The story</a>
        <a href="/#problems">What's holding you back</a>
        <a href="/#how-i-work">How I work</a>
        <a href="/#research">Research</a>
        <a href="/#about">About</a>
        <a href="/#faqs">FAQs</a>
        {insights}
      </nav>
      <a href="{CALENDLY_URL}" target="_blank" rel="noopener" class="btn btn-dark nav-cta">Book a clarity conversation</a>
      <button class="nav-toggle" aria-label="Toggle menu" aria-expanded="false" aria-controls="mobile-menu">
        <span></span><span></span><span></span>
      </button>
    </div>
    <nav class="mobile-menu" id="mobile-menu" aria-label="Main (mobile)">
      <a href="/#story">The story</a>
      <a href="/#problems">What's holding you back</a>
      <a href="/#how-i-work">How I work</a>
      <a href="/#research">Research</a>
      <a href="/#about">About</a>
      <a href="/#faqs">FAQs</a>
      {insights}
      <a href="{CALENDLY_URL}" target="_blank" rel="noopener" class="btn btn-dark">Book a clarity conversation</a>
    </nav>
  </header>
</div>

<main id="main">
{body}
</main>

<footer class="site-footer">
  <div class="container footer-inner">
    <p class="footer-name">Veloxitas — Yasmin Khataie · Dubai, UAE</p>
    <p class="footer-tagline">Strategy for established B2B organisations whose marketing has stopped working, or who are ready to change how they&rsquo;re seen.</p>
    <nav class="footer-links" aria-label="Footer">
      <a href="{LINKEDIN_URL}" target="_blank" rel="noopener">LinkedIn</a>
      <a href="{CALENDLY_URL}" target="_blank" rel="noopener">Book a clarity conversation</a>
      {insights}
    </nav>
    <p class="footer-copy">&copy; 2026 Veloxitas</p>
  </div>
</footer>

<script src="/script.js"></script>
</body>
</html>
"""


def social_head(title, description, url, image, og_type):
    return f"""<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}">
<link rel="canonical" href="{esc(abs_url(url))}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(description)}">
<meta property="og:url" content="{esc(abs_url(url))}">
<meta property="og:type" content="{og_type}">
<meta property="og:image" content="{esc(abs_url(image))}">
<meta name="twitter:card" content="summary_large_image">"""


def render_index(posts):
    if posts:
        items = "\n".join(f"""      <li class="insight-item">
        <h2><a href="{p['url']}">{esc(p['title'])}</a></h2>
        <p class="insight-meta"><time datetime="{p['date'].isoformat()}">{human_date(p['date'])}</time></p>
        <p>{esc(p['description'])}</p>
      </li>""" for p in posts)
        listing = f'    <ul class="insight-list">\n{items}\n    </ul>'
    else:
        listing = '    <p class="insight-empty">The first articles are on their way.</p>'
    head = social_head(INSIGHTS_TITLE, INSIGHTS_INTRO, "/insights/", DEFAULT_IMAGE, "website")
    head += "\n" + json_ld({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE_URL + "/"},
            {"@type": "ListItem", "position": 2, "name": "Insights", "item": SITE_URL + "/insights/"},
        ],
    })
    body = f"""
  <section class="insights-page">
    <div class="container insights-container">
    <h1>Insights</h1>
    <p class="insights-intro">{esc(INSIGHTS_INTRO)}</p>
{listing}
    </div>
  </section>
"""
    return page(head, body, bool(posts))


def render_post(post, posts):
    url = post["url"]
    title_tag = f"{post['title']} | Veloxitas"
    head = social_head(title_tag, post["description"], url, post["image"], "article")
    head += f'\n<meta property="article:published_time" content="{post["date"].isoformat()}">'
    head += f'\n<meta property="article:modified_time" content="{post["updated"].isoformat()}">'
    head += "\n" + json_ld({
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE_URL + "/"},
            {"@type": "ListItem", "position": 2, "name": "Insights", "item": SITE_URL + "/insights/"},
            {"@type": "ListItem", "position": 3, "name": post["title"], "item": abs_url(url)},
        ],
    })
    head += "\n" + json_ld({
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": post["title"],
        "description": post["description"],
        "author": {"@type": "Person", "@id": SITE_URL + "/#yasmin", "name": "Yasmin Khataie"},
        "publisher": {"@type": "Organization", "@id": SITE_URL + "/#org", "name": "Veloxitas"},
        "datePublished": post["date"].isoformat(),
        "dateModified": post["updated"].isoformat(),
        "image": abs_url(post["image"]),
        "mainEntityOfPage": abs_url(url),
    })

    faq_html = ""
    if post["faq"]:
        head += "\n" + json_ld({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": [{
                "@type": "Question",
                "name": str(item["q"]).strip(),
                "acceptedAnswer": {"@type": "Answer", "text": str(item["a"]).strip()},
            } for item in post["faq"]],
        })
        items = "\n".join(f"""        <div class="faq-item">
          <h3>{esc(str(item['q']).strip())}</h3>
          <p>{esc(str(item['a']).strip())}</p>
        </div>""" for item in post["faq"])
        faq_html = f"""
      <section class="article-faq" aria-labelledby="article-faq-heading">
        <h2 id="article-faq-heading">FAQs</h2>
{items}
      </section>
"""

    related = related_posts(post, posts)
    related_html = ""
    if related:
        items = "\n".join(f"""          <li><a href="{p['url']}">{esc(p['title'])}</a>
            <span class="insight-meta">{human_date(p['date'])}</span></li>""" for p in related)
        related_html = f"""
      <aside class="article-related" aria-labelledby="related-heading">
        <h2 id="related-heading">Related articles</h2>
        <ul>
{items}
        </ul>
      </aside>
"""

    body = f"""
  <article class="article-page">
    <div class="container article-container">
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <ol>
          <li><a href="/">Home</a></li>
          <li><a href="/insights/">Insights</a></li>
          <li aria-current="page">{esc(post['title'])}</li>
        </ol>
      </nav>

      <h1>{esc(post['title'])}</h1>
      <p class="article-byline">By Yasmin Khataie · Published <time datetime="{post['date'].isoformat()}">{human_date(post['date'])}</time> · Updated <time datetime="{post['updated'].isoformat()}">{human_date(post['updated'])}</time></p>

      <div class="short-answer">
        <p class="short-answer-label">Short answer</p>
        <p>{esc(post['short_answer'])}</p>
      </div>

      <div class="article-body">
{post['body']}
      </div>
{faq_html}
      <aside class="author-box" aria-label="About the author">
        <img src="/assets/about-me-new.webp" alt="Portrait of Yasmin Khataie" width="900" height="879" loading="lazy" decoding="async">
        <div>
          <p class="author-name">Yasmin Khataie</p>
          <p>{esc(AUTHOR_BIO)}</p>
          <a href="{LINKEDIN_URL}" target="_blank" rel="noopener">Yasmin on LinkedIn</a>
        </div>
      </aside>

      <div class="article-cta">
        <p>If this sounds like your company, let&rsquo;s talk.</p>
        <a href="{CALENDLY_URL}" target="_blank" rel="noopener" class="btn btn-teal">Book a clarity conversation</a>
      </div>
{related_html}
    </div>
  </article>
"""
    return page(head, body, True)


def render_feed(posts):
    def rfc822(d):
        return format_datetime(dt.datetime(d.year, d.month, d.day, 9, 0, tzinfo=dt.timezone.utc))

    items = "\n".join(f"""    <item>
      <title>{esc(p['title'])}</title>
      <link>{abs_url(p['url'])}</link>
      <guid isPermaLink="true">{abs_url(p['url'])}</guid>
      <pubDate>{rfc822(p['date'])}</pubDate>
      <description>{esc(p['description'])}</description>
    </item>""" for p in posts)
    build_date = rfc822(posts[0]["updated"]) if posts else rfc822(dt.date(2026, 10, 2))
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Veloxitas Insights</title>
    <link>{SITE_URL}/insights/</link>
    <description>{esc(INSIGHTS_INTRO)}</description>
    <language>en</language>
    <lastBuildDate>{build_date}</lastBuildDate>
    <atom:link href="{SITE_URL}/insights/feed.xml" rel="self" type="application/rss+xml"/>
{items}
  </channel>
</rss>
"""


def render_sitemap(posts, home_lastmod):
    insights_lastmod = max([home_lastmod] + [p["updated"] for p in posts]) if posts else home_lastmod
    urls = [(SITE_URL + "/", home_lastmod), (SITE_URL + "/insights/", insights_lastmod)]
    urls += [(abs_url(p["url"]), p["updated"]) for p in posts]
    entries = "\n".join(f"""  <url>
    <loc>{esc(loc)}</loc>
    <lastmod>{lastmod.isoformat()}</lastmod>
  </url>""" for loc, lastmod in urls)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{entries}
</urlset>
"""


def homepage_faq_jsonld(index_html):
    section = re.search(r'<section class="faqs" id="faqs">(.*?)</section>', index_html, re.S)
    if not section:
        sys.exit("index.html: FAQ section not found")
    pairs = re.findall(r'<div class="faq-item">\s*<h3>(.*?)</h3>\s*<p>(.*?)</p>\s*</div>', section.group(1), re.S)
    if not pairs:
        sys.exit("index.html: no FAQ items found")

    def text(fragment):
        return " ".join(html.unescape(re.sub(r"<[^>]+>", "", fragment)).split())

    return json_ld({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [{
            "@type": "Question",
            "name": text(q),
            "acceptedAnswer": {"@type": "Answer", "text": text(a)},
        } for q, a in pairs],
    })


# ---------------------------------------------------------------- main

def build(out_dir, include_drafts):
    posts = load_posts(include_drafts)
    files = {}

    index_path = ROOT / "index.html"
    index_html = index_path.read_text(encoding="utf-8")
    index_html = replace_block(index_html, "FAQ_JSONLD", homepage_faq_jsonld(index_html))
    index_html = replace_block(index_html, "NAV_INSIGHTS", nav_insights_link(bool(posts)))
    files["index.html"] = index_html

    files["insights/index.html"] = render_index(posts)
    files["insights/feed.xml"] = render_feed(posts)
    for p in posts:
        files[f"insights/{p['slug']}/index.html"] = render_post(p, posts)
    files["sitemap.xml"] = render_sitemap(posts, git_date(index_path))

    # article folders generated earlier whose source is gone (or became a draft)
    stale = []
    insights_out = out_dir / "insights"
    if insights_out.is_dir():
        for d in insights_out.iterdir():
            page_file = d / "index.html"
            if d.is_dir() and f"insights/{d.name}/index.html" not in files and page_file.is_file() \
                    and GENERATED_MARK in page_file.read_text(encoding="utf-8"):
                stale.append(d)
    return files, stale


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="exit 1 if generated files are out of date")
    parser.add_argument("--drafts", action="store_true", help="include draft articles (preview only)")
    parser.add_argument("--out", type=Path, default=ROOT, help="output directory (default: repo root)")
    args = parser.parse_args()

    out_dir = args.out.resolve()
    if args.drafts and out_dir == ROOT:
        sys.exit("--drafts writes unpublished articles; use it with --out <preview folder>")

    if out_dir != ROOT and not args.check:
        # preview build: start from a copy of the static site so pages render
        shutil.copytree(ROOT, out_dir, dirs_exist_ok=True,
                        ignore=shutil.ignore_patterns(".git", ".github", "content", "scripts",
                                                      "backup-original-design"))

    files, stale = build(out_dir, args.drafts)
    changed = [rel for rel, content in files.items()
               if not (out_dir / rel).is_file() or (out_dir / rel).read_text(encoding="utf-8") != content]

    if args.check:
        problems = changed + [f"{d.relative_to(out_dir)}/ (stale)" for d in stale]
        if problems:
            print("Out of date (run python3 scripts/build.py):\n  " + "\n  ".join(problems))
            sys.exit(1)
        print("Generated files are up to date.")
        return

    for rel in changed:
        target = out_dir / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(files[rel], encoding="utf-8")
        print(f"wrote {rel}")
    for d in stale:
        shutil.rmtree(d)
        print(f"removed {d.relative_to(out_dir)}/")
    if not changed and not stale:
        print("Nothing to do: generated files are up to date.")


if __name__ == "__main__":
    main()
